
const LogoData = [
 {
    id: 1,
    image: ('../../src/images/logoDesign/abstract-yellow/abstract-yellow-0.jpg'),
    name: "Abstract yellow",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/abstract-yellow/abstract-yellow-1.jpg",
    alt_2: "../../src/images/logoDesign/abstract-yellow/abstract-yellow-2.jpg",
    alt_3: "../../src/images/logoDesign/abstract-yellow/abstract-yellow-3.jpg",
    alt_4: "../../src/images/logoDesign/abstract-yellow/abstract-yellow-4.jpg",
},
{
    id: 2,
    image: '../../src/images/logoDesign/black-white/black-white-0.jpg',
    name: "Black white",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/black-white/black-white-1.jpg",
    alt_2: "../../src/images/logoDesign/black-white/black-white-2.jpg",
    alt_3: "../../src/images/logoDesign/black-white/black-white-3.jpg",
    alt_4: "../../src/images/logoDesign/black-white/black-white-4.jpg",
},
{
    id: 3,
    image: '../../src/images/logoDesign/city-night/city-night-0.jpg',
    name: "City night",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/city-night/city-night-1.jpg",
    alt_2: "../../src/images/logoDesign/city-night/city-night-2.jpg",
    alt_3: "../../src/images/logoDesign/city-night/city-night-3.jpg",
    alt_4: "../../src/images/logoDesign/city-night/city-night-4.jpg",
},
{
    id: 4,
    image: '../../src/images/logoDesign/curious-cat/curious-cat-0.jpg',
    name: "Curious cat",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/curious-cat/curious-cat-1.jpg",
    alt_2: "../../src/images/logoDesign/curious-cat/curious-cat-2.jpg",
    alt_3: "../../src/images/logoDesign/curious-cat/curious-cat-3.jpg",
    alt_4: "../../src/images/logoDesign/curious-cat/curious-cat-4.jpg",
},
{
    id: 5,
    image: '../../src/images/logoDesign/green-tv/green-tv-0.jpg',
    name: "Green tv",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/green-tv/green-tv-1.jpg",
    alt_2: "../../src/images/logoDesign/green-tv/green-tv-2.jpg",
    alt_3: "../../src/images/logoDesign/green-tv/green-tv-3.jpg",
    alt_4: "../../src/images/logoDesign/green-tv/green-tv-4.jpg",
},
{
    id: 6,
    image: '../../src/images/logoDesign/greenry-flower/greenry-flower-0.jpg',
    name: "Greenary flower",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/greenry-flower/greenry-flower-1.jpg",
    alt_2: "../../src/images/logoDesign/greenry-flower/greenry-flower-2.jpg",
    alt_3: "../../src/images/logoDesign/greenry-flower/greenry-flower-3.jpg",
    alt_4: "../../src/images/logoDesign/greenry-flower/greenry-flower-4.jpg",
},
{
    id: 7,
    image: '../../src/images/logoDesign/iphone-xr/iphone-xr-0.jpg',
    name: "Iphone xr",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/iphone-xr/iphone-xr-1.jpg",
    alt_2: "../../src/images/logoDesign/iphone-xr/iphone-xr-2.jpg",
    alt_3: "../../src/images/logoDesign/iphone-xr/iphone-xr-3.jpg",
    alt_4: "../../src/images/logoDesign/iphone-xr/iphone-xr-4.jpg",
},
{
    id: 8,
    image: '../../src/images/logoDesign/kabuto-dragon/kabuto-dragon-0.jpg',
    name: "Kabuto dragon",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/kabuto-dragon/kabuto-dragon-1.jpg",
    alt_2: "../../src/images/logoDesign/kabuto-dragon/kabuto-dragon-2.jpg",
    alt_3: "../../src/images/logoDesign/kabuto-dragon/kabuto-dragon-3.jpg",
    alt_4: "../../src/images/logoDesign/kabuto-dragon/kabuto-dragon-4.jpg",
},
{
    id: 9,
    image: '../../src/images/logoDesign/lightening-sand/lightening-sand-0.jpg',
    name: "Lightening sand",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/lightening-sand/lightening-sand-1.jpg",
    alt_2: "../../src/images/logoDesign/lightening-sand/lightening-sand-2.jpg",
    alt_3: "../../src/images/logoDesign/lightening-sand/lightening-sand-3.jpg",
    alt_4: "../../src/images/logoDesign/lightening-sand/lightening-sand-4.jpg",
},
{
    id: 10,
    image: '../../src/images/logoDesign/live-concert/live-concert-0.jpg',
    name: "Live concert",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/live-concert/live-concert-1.jpg",
    alt_2: "../../src/images/logoDesign/live-concert/live-concert-2.jpg",
    alt_3: "../../src/images/logoDesign/live-concert/live-concert-3.jpg",
    alt_4: "../../src/images/logoDesign/live-concert/live-concert-4.jpg",
},
{
    id: 11,
    image: '../../src/images/logoDesign/lonely-house/lonely-house-0.jpg',
    name: "Lonely house",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/lonely-house/lonely-house-1.jpg",
    alt_2: "../../src/images/logoDesign/lonely-house/lonely-house-2.jpg",
    alt_3: "../../src/images/logoDesign/lonely-house/lonely-house-3.jpg",
    alt_4: "../../src/images/logoDesign/lonely-house/lonely-house-4.jpg",
},
{
    id: 12,
    image: '../../src/images/logoDesign/mini-wen/mini-wen-0.jpg',
    name: "Mini wen",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/mini-wen/mini-wen-1.jpg",
    alt_2: "../../src/images/logoDesign/mini-wen/mini-wen-2.jpg",
    alt_3: "../../src/images/logoDesign/mini-wen/mini-wen-3.jpg",
    alt_4: "../../src/images/logoDesign/mini-wen/mini-wen-4.jpg",
},
{
    id: 13,
    image: '../../src/images/logoDesign/nature-sports/nature-sports-0.jpg',
    name: "Nature sports",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/nature-sports/nature-sports-1.jpg",
    alt_2: "../../src/images/logoDesign/nature-sports/nature-sports-2.jpg",
    alt_3: "../../src/images/logoDesign/nature-sports/nature-sports-3.jpg",
    alt_4: "../../src/images/logoDesign/nature-sports/nature-sports-4.jpg",
},
{
    id: 14,
    image: '../../src/images/logoDesign/nice-decoration/nice-decoration-0.jpg',
    name: "Nice decoration",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/nice-decoration/nice-decoration-1.jpg",
    alt_2: "../../src/images/logoDesign/nice-decoration/nice-decoration-2.jpg",
    alt_3: "../../src/images/logoDesign/nice-decoration/nice-decoration-3.jpg",
    alt_4: "../../src/images/logoDesign/nice-decoration/nice-decoration-4.jpg",
},
{
    id: 15,
    image: '../../src/images/logoDesign/night-fog/night-fog-0.jpg',
    name: "Night fog",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/night-fog/night-fog-1.jpg",
    alt_2: "../../src/images/logoDesign/night-fog/night-fog-2.jpg",
    alt_3: "../../src/images/logoDesign/night-fog/night-fog-3.jpg",
    alt_4: "../../src/images/logoDesign/night-fog/night-fog-4.jpg",
},
{
    id: 16,
    image: '../../src/images/logoDesign/night-light/night-light-0.jpg',
    name: "Night light",
    type: "logo",
    date: "10 7 2023",
    info: "Colorful geometric seamless repetitive vector curvy waves pattern texture background. Vector graphic illustration.",
    alt_1: "../../src/images/logoDesign/night-light/night-light-1.jpg",
    alt_2: "../../src/images/logoDesign/night-light/night-light-2.jpg",
    alt_3: "../../src/images/logoDesign/night-light/night-light-3.jpg",
    alt_4: "../../src/images/logoDesign/night-light/night-light-4.jpg",
},
]
export default LogoData ;
